framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'no-reply@demo.fr'
        headers:
            From: '%app.name% <no-reply@demo.fr>'
            X-Custom-Header: '%app.name%'
