twig:
    file_name_pattern: '*.twig'
    form_themes: 
        - 'bootstrap_5_layout.html.twig'
        - 'form/form.html.twig'

    globals:
        app_name: '%app.name%'
        app_logo_path: '%app.logo_path%'

    paths:
        '%app.assets_dir%/images': images
        '%app.assets_dir%/styles': styles

when@test:
    twig:
        strict_variables: true
