twig:
    file_name_pattern: '*.twig'
    form_themes: 
        - 'bootstrap_5_layout.html.twig'

    globals:
        app_name: '%app.name%'
        app_logo_path: '%app.logo_path%'

when@test:
    twig:
        strict_variables: true
