ux_icons:
    icon_dir: '%kernel.project_dir%/assets/icons'
    default_icon_attributes:
        fill: currentColor
        aria-hidden: true
        width: '16'
        height: '16'
        class: 'mb-1'
    aliases:
        book: bi:book
        category: bi:inboxes
        danger: bi:radioactive
        delete: bi:trash
        gear: bi:gear
        fingerprint: bi:fingerprint
        hierarchy: bi:diagram-3
        home: bi:house
        info: bi:info-circle-fill
        info-circle: bi:info-circle
        list: bi:card-list
        login: bi:box-arrow-in-right
        logout: bi:box-arrow-right
        mail: bi:envelope
        new: bi:plus-circle
        phone: bi:telephone
        pointer: bi:hand-index-thumb
        profile: bi:person-vcard-fill
        register: bi:person-fill-add
        reload: bi:arrow-clockwise
        save: bi:save
        success: bi:check-circle-fill
        user: bi:person
        users: bi:people