ux_icons:
    icon_dir: '%kernel.project_dir%/assets/icons'
    default_icon_attributes:
        fill: currentColor
        aria-hidden: true
        width: '16'
        height: '16'
        class: 'mb-1'
    aliases:
        book: bi:book
        category: bi:inboxes
        gear: bi:gear
        hierarchy: bi:diagram-3
        home: bi:house
        list: bi:card-list
        new: bi:plus-circle