ux_icons:
    icon_dir: '%app.assets_dir%/icons'
    default_icon_attributes:
        fill: currentColor
        aria-hidden: true
        width: '16'
        height: '16'
        class: 'mb-1'
    aliases:
        activity: bi:activity
        book: bi:book
        bookmark: bi:bookmark
        category: bi:inboxes
        chart-line: bi:graph-up
        chart-bar: bi:bar-chart-line-fill
        chart-pie: bi:pie-chart-fill
        close: bi:x-square-fill
        danger: bi:radioactive
        dashboard: bi:speedometer2
        delete: bi:trash
        event: bi:calendar-event
        eye: bi:eye
        filter: bi:funnel
        filter-f: bi:funnel-fill
        gear: bi:gear
        fingerprint: bi:fingerprint
        hierarchy: bi:diagram-3
        home: bi:house
        info: bi:info-circle-fill
        info-circle: bi:info-circle
        list: bi:card-list
        login: bi:box-arrow-in-right
        logout: bi:box-arrow-right
        mail: bi:envelope
        mysql: logos:mysql
        new: bi:plus-circle
        paperclip: bi:paperclip
        pdf: bi:file-earmark-pdf
        phone: bi:telephone
        php: logos:php
        pointer: bi:hand-index-thumb
        profile: bi:person-vcard-fill
        register: bi:person-fill-add
        reload: bi:arrow-clockwise
        save: bi:save
        search: bi:search
        send: bi:send-fill
        success: bi:check-circle-fill
        table: bi:table
        twig: material-icon-theme:twig
        user: bi:person
        users: bi:people
        watch: bi:watch
        window: bi:window